<#
.SYNOPSIS
    Prepares a stable `forgeos` command on Windows from a ForgeOS directory you already have.

.DESCRIPTION
    READ THIS BEFORE YOU RUN IT. That is not a courtesy line -- it is the whole design. This file
    fetches nothing, so there is no version of it that could execute code you have not seen. The
    unsafe remote-pipe install shape is refused by this project's own hook, and a product may not
    ask its users to do what its own hook refuses.

    WHAT IT DOES. It writes two small shims -- forgeos.cmd and forgeos.ps1 -- into a directory you
    name, each pointing at the ForgeOS checkout or extracted artifact you name. That is all. It is
    not a machine-wide install: nothing is elevated, no registry key is written, and PATH is never
    changed.

    WHY A SHIM AND NOT AN INSTALL. ForgeOS is a directory of scripts, not a binary. What is missing
    on a fresh machine is not the software -- it is a short way to type it. A shim supplies exactly
    that and stays reversible: deleting the two files undoes it completely.

    PATH IS REPORTED, NEVER CHANGED. The destination's PATH line is printed for you to add if you
    want it. A tool that edits PATH behind your back has made a durable change to your machine to
    save you one command.

    DRY RUN IS THE DEFAULT. Without -Apply this reports what it would write and writes nothing --
    the same rule adopt and update follow.

    INTEGRITY. When a .sha256 file sits beside the source (the release-artifact case) it is verified
    and a mismatch FAILS CLOSED. When the source is a git checkout there is no such file, and this
    says so rather than quietly skipping the step.

    -Force is not a parameter here and is never passed to anything. The flag that overwrites a
    project's customized files has no route through this installer.

.PARAMETER Source
    The ForgeOS directory to point at: an extracted release artifact or a checkout. Defaults to the
    repository this script sits in.

.PARAMETER Destination
    Where to write the two shims. Required for -Apply and for -Uninstall.

.PARAMETER Apply
    Write the shims. Without it, this is a dry run.

.PARAMETER Uninstall
    Remove shims previously written here. Only files carrying this installer's marker are removed;
    anything else in the destination is left alone and reported.

.PARAMETER Json
    Emit JSON on stdout and nothing else.

.PARAMETER Help
    Print this usage on stdout and exit 0, reading nothing and writing nothing. Also reachable as
    -h, --help and /?, because those are what people actually type. Not -?: PowerShell intercepts
    that one itself and this script never runs -- see the note above the help gate.

.NOTES
    Windows only, and it says so: the POSIX installer is a separate, unbuilt phase.
    Exit 0 reported -- asking for help is reporting, so help exits 0, not 1.
    Exit 1 usage error, missing source, bad destination, or integrity mismatch.
#>
param(
    [string]$Source = '',
    [string]$Destination = '',
    [switch]$Apply,
    [switch]$Uninstall,
    [switch]$Json,
    [switch]$Help,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$Rest
)

Set-StrictMode -Version 2.0
try { [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false) } catch { }
$ErrorActionPreference = 'Stop'

# The line that makes a shim identifiable as ours. Uninstall removes a file only if it carries this,
# so an installer can never delete something a person put in the destination by hand.
$MARKER = 'ForgeOS shim -- generated by scripts/install/install-forgeos.ps1'

# SHA-256 WITHOUT A CMDLET, and that is the whole point of this function existing.
#
# Get-FileHash lives in Microsoft.PowerShell.Utility and is found by module autoloading, which
# depends on PSModulePath. A child Windows PowerShell 5.1 process launched from a PowerShell 7
# parent INHERITS the parent's PSModulePath -- which points at PowerShell 7's module tree -- so 5.1
# cannot find its own modules and the cmdlet is simply not there:
#
#   The term 'Get-FileHash' is not recognized ... CommandNotFoundException
#
# That is not a CI quirk. Anyone who runs this installer from a PowerShell 7 session through
# Start-Process gets the same inheritance and the same failure, and the failure lands on the ONE
# branch that must never be skipped: the integrity check. The .NET type is always present, needs no
# module, and behaves identically on 5.1 and 7.
function Get-Sha256Hex {
    param([string]$Path)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $stream = [System.IO.File]::OpenRead($Path)
        try { $bytes = $sha.ComputeHash($stream) } finally { $stream.Dispose() }
    } finally {
        $sha.Dispose()
    }
    # Lowercase hex, matching the sha256sum format the .sha256 file carries.
    return -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

function Show-Usage {
    return @(
        'install-forgeos -- prepare a local `forgeos` command on Windows',
        '',
        'Usage:',
        '  install-forgeos.ps1 -Destination <dir> [-Source <dir>] [-Apply] [-Json]',
        '  install-forgeos.ps1 -Destination <dir> -Uninstall [-Apply] [-Json]',
        '  install-forgeos.ps1 -Help',
        '',
        'Writes two shims into -Destination and nothing else. DRY RUN unless -Apply is given.',
        'PATH is never changed: the line to add is reported for you to apply yourself.',
        'It fetches nothing, and -Force is neither accepted nor passed.',
        '',
        'Windows only. The POSIX installer is a separate phase and is not built.',
        '',
        'Exit codes: 0 reported, help included - 1 usage error, missing source, bad destination,',
        '            or bad checksum.'
    )
}

# --- help: the only path that exits 0 without doing anything -------------------------------------
# Asking what a program does is not a usage error, and answering it on stderr with exit 1 -- which
# is what this did until now -- tells every script that reads exit codes that the question failed.
#
# The spellings arrive by three different routes, which is why one check cannot sit in one place:
# -Help binds as a parameter and -h binds to it too (PowerShell matches parameter prefixes, and no
# other parameter here starts with h); --help is not PowerShell syntax at all, so it falls into
# $Rest; and /? does not start with a dash, so it binds POSITIONALLY into $Source -- as does a bare
# `help`, which the forgeos command surface already accepts and which used to produce the baffling
# "Source is not a directory: help". Anyone arriving from cmd or from a POSIX shell types one of
# these, and all of them now land here.
#
# -? IS DELIBERATELY ABSENT and must not be added: powershell.exe intercepts it for any script
# carrying a comment-based help block like this one's, renders its own help, and exits 0 without
# ever running the file. Listing it here would be a claim this script cannot keep -- a token that
# looks handled, prints nothing, and is unreachable from inside. Proven by giving -? to a script
# with no help block, which runs its body normally, and to this one, which never starts.
#
# This gate sits above every other step on purpose. Nothing below it has run yet: no source has
# been resolved, no checksum read, no destination inspected, nothing written. Help therefore cannot
# require -Source or -Destination, cannot fail on a bad one, and cannot touch the disk.
$helpTokens = @('--help', '/?', 'help')
$wantsHelp = [bool]$Help
foreach ($t in @($Rest)) {
    if ($t -and ($helpTokens -contains $t)) { $wantsHelp = $true }
}
# -contains is case-insensitive here, which is wanted: --HELP is the same question.
if ($Source -and ($helpTokens -contains $Source)) { $wantsHelp = $true }
if ($wantsHelp) {
    # stdout, not stderr: this is the answer, not a complaint about the question.
    Show-Usage | ForEach-Object { Write-Output $_ }
    exit 0
}

if (@($Rest | Where-Object { $_ }).Count -gt 0) {
    [Console]::Error.WriteLine('Unknown option: ' + (@($Rest) -join ' '))
    [Console]::Error.WriteLine('')
    Show-Usage | ForEach-Object { [Console]::Error.WriteLine($_) }
    exit 1
}

$here = $PSScriptRoot
$notes = New-Object System.Collections.Generic.List[string]

# --- the source ---------------------------------------------------------------------------------
if (-not $Source) { $Source = (Resolve-Path -LiteralPath (Join-Path $here '..\..')).Path }
if (-not (Test-Path -LiteralPath $Source -PathType Container)) {
    [Console]::Error.WriteLine("Source is not a directory: $Source")
    exit 1
}
$srcRoot = (Resolve-Path -LiteralPath $Source).Path

# A source is only a ForgeOS if it carries the command this installer points at. Checking for the
# entry point rather than for a name means a renamed directory still works and an empty one does not.
$srcCmd = Join-Path $srcRoot 'scripts\command\forgeos.ps1'
if (-not (Test-Path -LiteralPath $srcCmd)) {
    [Console]::Error.WriteLine("Source does not look like ForgeOS (no scripts\command\forgeos.ps1): $srcRoot")
    [Console]::Error.WriteLine('Point -Source at an extracted release artifact or a checkout.')
    exit 1
}

$srcVersion = 'unknown'
$bp = Join-Path $srcRoot 'blueprint.version'
if (Test-Path -LiteralPath $bp) {
    try {
        $doc = Get-Content -LiteralPath $bp -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($doc.version) { $srcVersion = $doc.version }
    } catch { }
} else {
    $notes.Add('the source has no blueprint.version, so the version it installs is unknown')
}

# --- integrity ----------------------------------------------------------------------------------
# A published artifact ships a .sha256 beside it. A checkout does not, and saying so is the point:
# a verification step that silently does nothing is worse than one that reports it had nothing to do.
$integrity = 'none'
$integrityDetail = 'no checksum file was found beside the source'
$archive = $null
foreach ($cand in @(Get-ChildItem -LiteralPath (Split-Path -Parent $srcRoot) -Filter '*.tar.gz.sha256' -File -ErrorAction SilentlyContinue)) {
    $archive = $cand
    break
}
if ($archive) {
    $expected = ''
    $named = ''
    try {
        $line = (Get-Content -LiteralPath $archive.FullName -First 1 -ErrorAction SilentlyContinue)
        if ($line -match '^([0-9a-fA-F]{64})\s+\*?(.+)$') { $expected = $Matches[1].ToLower(); $named = $Matches[2].Trim() }
    } catch { }
    $target = Join-Path (Split-Path -Parent $srcRoot) $named
    if (-not $expected) {
        $integrity = 'unreadable'
        $integrityDetail = "the checksum file beside the source could not be parsed: $($archive.Name)"
    } elseif (-not (Test-Path -LiteralPath $target)) {
        $integrity = 'unverified'
        $integrityDetail = "a checksum file names $named, but that archive is not beside it"
    } else {
        $actual = Get-Sha256Hex -Path $target
        if ($actual -eq $expected) {
            $integrity = 'verified'
            $integrityDetail = "$named matches its published SHA-256"
        } else {
            # FAIL CLOSED. This is the one branch that must never become a warning.
            [Console]::Error.WriteLine('Checksum mismatch. Refusing to install.')
            [Console]::Error.WriteLine("  archive  : $target")
            [Console]::Error.WriteLine("  expected : $expected")
            [Console]::Error.WriteLine("  actual   : $actual")
            exit 1
        }
    }
} else {
    $integrityDetail = 'no checksum file beside the source; a git checkout gets its integrity from git instead'
}

# --- the destination ----------------------------------------------------------------------------
if (-not $Destination) {
    [Console]::Error.WriteLine('-Destination <dir> is required: where the forgeos shims should be written.')
    [Console]::Error.WriteLine('')
    Show-Usage | ForEach-Object { [Console]::Error.WriteLine($_) }
    exit 1
}
$destParent = Split-Path -Parent $Destination
if ($destParent -and -not (Test-Path -LiteralPath $destParent -PathType Container)) {
    [Console]::Error.WriteLine("Destination's parent directory does not exist: $destParent")
    exit 1
}
$destFull = $Destination
if (Test-Path -LiteralPath $Destination) { $destFull = (Resolve-Path -LiteralPath $Destination).Path }

# Writing shims into the ForgeOS directory itself would put a copy of the command beside the command.
if ($destFull.TrimEnd('\') -eq $srcRoot.TrimEnd('\')) {
    [Console]::Error.WriteLine('Destination and source are the same directory. Choose a separate directory for the shims.')
    exit 1
}

$shimCmd = Join-Path $destFull 'forgeos.cmd'
$shimPs1 = Join-Path $destFull 'forgeos.ps1'

function Test-OurShim {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) { return $false }
    try { return ((Get-Content -LiteralPath $Path -Raw -ErrorAction SilentlyContinue) -match [regex]::Escape($MARKER)) }
    catch { return $false }
}

# A file in the destination that is NOT ours is never touched, in either mode. The installer owns
# what it wrote and nothing else.
$blockers = New-Object System.Collections.Generic.List[string]
foreach ($p in @($shimCmd, $shimPs1)) {
    if ((Test-Path -LiteralPath $p) -and -not (Test-OurShim -Path $p)) {
        $blockers.Add("$(Split-Path -Leaf $p) exists in the destination and was not written by this installer; it is left untouched")
    }
}

# --- PATH: reported, never changed ---------------------------------------------------------------
$onPath = $false
try {
    foreach ($entry in ($env:PATH -split ';')) {
        if ($entry -and $entry.TrimEnd('\') -ieq $destFull.TrimEnd('\')) { $onPath = $true; break }
    }
} catch { }

$mode = 'dry-run'
if ($Apply) { $mode = 'apply' }
$action = 'install'
if ($Uninstall) { $action = 'uninstall' }

$written = New-Object System.Collections.Generic.List[string]
$removed = New-Object System.Collections.Generic.List[string]
$planned = New-Object System.Collections.Generic.List[string]

if ($Uninstall) {
    foreach ($p in @($shimCmd, $shimPs1)) {
        if (Test-OurShim -Path $p) {
            $planned.Add($p)
            if ($Apply) { [System.IO.File]::Delete($p); $removed.Add($p) }
        }
    }
} else {
    if ($blockers.Count -eq 0) {
        $planned.Add($shimCmd)
        $planned.Add($shimPs1)
    }
    if ($Apply -and $blockers.Count -eq 0) {
        if (-not (Test-Path -LiteralPath $destFull)) { New-Item -ItemType Directory -Path $destFull | Out-Null }
        # The shims carry no logic of their own beyond locating the command. Anything smarter here
        # would be a second implementation of the wrapper, and the two would drift.
        # Every concatenation is parenthesised, and that is load-bearing. In PowerShell the comma
        # binds TIGHTER than +, so @('a', 'b' + $x, 'c') parses as ('a','b') + ($x,'c') and
        # flattens into four elements instead of three. Written without these brackets, each shim
        # line was split at its + and the .cmd invoked an interactive PowerShell instead of the
        # command -- which is exactly what it did before this was found.
        $cmdBody = @(
            '@echo off',
            ('rem ' + $MARKER),
            ('rem source: ' + $srcRoot),
            ('powershell.exe -NoProfile -ExecutionPolicy Bypass -File "' + $srcCmd + '" %*')
        )
        Set-Content -LiteralPath $shimCmd -Value $cmdBody -Encoding ASCII
        $written.Add($shimCmd)
        $ps1Body = @(
            ('# ' + $MARKER),
            ('# source: ' + $srcRoot),
            'param([Parameter(ValueFromRemainingArguments = $true)][string[]]$ForgeosArgs)',
            ('& powershell.exe -NoProfile -ExecutionPolicy Bypass -File "' + $srcCmd + '" @ForgeosArgs'),
            'exit $LASTEXITCODE'
        )
        Set-Content -LiteralPath $shimPs1 -Value $ps1Body -Encoding UTF8
        $written.Add($shimPs1)
    }
}

$exitCode = 0
if ($blockers.Count -gt 0 -and -not $Uninstall) { $exitCode = 1 }

if ($Json) {
    ([ordered]@{
        schema        = 'forgeos.install/1'
        platform      = 'windows'
        action        = $action
        mode          = $mode
        wouldWrite    = [bool]$Apply
        source        = $srcRoot
        sourceVersion = $srcVersion
        destination   = $destFull
        integrity     = $integrity
        integrityNote = $integrityDetail
        pathChanged   = $false
        destinationOnPath = $onPath
        pathLine      = $destFull
        plannedFiles  = @($planned)
        filesWritten  = @($written)
        filesRemoved  = @($removed)
        blockers      = @($blockers)
        notes         = @($notes)
        forcePassed   = $false
        safety        = [ordered]@{
            canModifyFiles          = [bool]$Apply
            canAuthorizeCode        = $false
            canOpenGovernanceWindow = $false
            changesPath             = $false
            reachesNetwork          = $false
        }
    }) | ConvertTo-Json -Depth 6
    exit $exitCode
}

Write-Output ''
Write-Output ('ForgeOS installer  [{0}]  {1}' -f $mode.ToUpper(), $action)
Write-Output ''
Write-Output ("  {0,-22} {1}" -f 'source', $srcRoot)
Write-Output ("  {0,-22} {1}" -f 'source version', $srcVersion)
Write-Output ("  {0,-22} {1}" -f 'destination', $destFull)
Write-Output ("  {0,-22} {1}  ({2})" -f 'integrity', $integrity, $integrityDetail)
Write-Output ''
if ($blockers.Count -gt 0) {
    Write-Output '  refusing to write:'
    foreach ($b in $blockers) { Write-Output ("    - {0}" -f $b) }
    Write-Output ''
}
if ($Uninstall) {
    if ($planned.Count -eq 0) {
        Write-Output '  nothing to remove: no shim written by this installer is present.'
    } else {
        foreach ($p in $planned) { Write-Output ("  {0,-22} {1}" -f $(if ($Apply) { 'removed' } else { 'would remove' }), $p) }
    }
} else {
    foreach ($p in $planned) { Write-Output ("  {0,-22} {1}" -f $(if ($Apply) { 'wrote' } else { 'would write' }), $p) }
}
Write-Output ''
Write-Output ("  {0,-22} {1}" -f 'PATH changed', 'no -- never, by design')
if ($onPath) {
    Write-Output ("  {0,-22} {1}" -f 'destination on PATH', 'yes')
} else {
    Write-Output ("  {0,-22} {1}" -f 'destination on PATH', 'no. To add it for this session:')
    Write-Output ('    $env:PATH = "' + $destFull + ';$env:PATH"')
}
foreach ($n in $notes) { Write-Output ("  note                   {0}" -f $n) }
Write-Output ''
if (-not $Apply) {
    Write-Output '  This was a DRY RUN. Nothing was written.'
    Write-Output '  To apply it:'
    if ($Uninstall) {
        Write-Output ('    powershell -NoProfile -ExecutionPolicy Bypass -File scripts/install/install-forgeos.ps1 -Destination ' + $destFull + ' -Uninstall -Apply')
    } else {
        Write-Output ('    powershell -NoProfile -ExecutionPolicy Bypass -File scripts/install/install-forgeos.ps1 -Destination ' + $destFull + ' -Apply')
    }
}
Write-Output ''
Write-Output '  This installer fetches nothing, changes no PATH, and never passes -Force.'
Write-Output ''
exit $exitCode
