#!/usr/bin/env bash
# Prepares a stable `forgeos` command on Linux from a ForgeOS directory you already have.
# POSIX counterpart of install-forgeos.ps1, case for case and refusal for refusal.
#
# READ THIS BEFORE YOU RUN IT. That is not a courtesy line -- it is the whole design. This file
# fetches nothing, so there is no version of it that could execute code you have not seen. The
# unsafe remote-pipe install shape is refused by this project's own hook, and a product may not ask
# its users to do what its own hook refuses.
#
# WHAT IT DOES. It writes one small launcher -- forgeos -- into a directory you name, pointing at
# the ForgeOS checkout or extracted artifact you name. That is all. It is not a system install:
# nothing is elevated, no package manager is involved, and PATH is never changed.
#
# WHY A LAUNCHER AND NOT AN INSTALL. ForgeOS is a directory of scripts, not a binary. What is
# missing on a fresh machine is not the software -- it is a short way to type it. A launcher supplies
# exactly that and stays reversible: deleting the one file undoes it completely.
#
# PATH IS REPORTED, NEVER CHANGED. The destination's PATH line is printed for you to add if you want
# it. A tool that edits your shell profile behind your back has made a durable change to your machine
# to save you one command.
#
# DRY RUN IS THE DEFAULT. Without --apply this reports what it would write and writes nothing -- the
# same rule adopt and update follow.
#
# INTEGRITY. When a .sha256 file sits beside the source (the release-artifact case) it is verified
# and a mismatch FAILS CLOSED. When the source is a git checkout there is no such file, and this says
# so rather than quietly skipping the step.
#
# --force is not an option here and is never passed to anything. The flag that overwrites a project's
# customized files has no route through this installer, which syncs no project files at all.
#
# PLATFORM HONESTY. Linux is what this claims. macOS is NOT claimed: open question 002 records that
# the POSIX half has never been exercised there, CI runs zero macOS jobs, and a channel may be
# described only at the rung it actually occupies. It very probably works; "probably" is not a rung.
#
# Usage: install-forgeos.sh --destination <dir> [--source <dir>] [--apply] [--json]
#        install-forgeos.sh --destination <dir> --uninstall [--apply] [--json]
#        install-forgeos.sh --help
# Exit 0 reported -- asking for help is reporting, so help exits 0, not 1.
# Exit 1 usage error, missing source, bad destination, or integrity mismatch.

set -uo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The line that makes a launcher identifiable as ours. Uninstall removes a file only if it carries
# this, so an installer can never delete something a person put in the destination by hand.
MARKER='ForgeOS launcher -- generated by scripts/install/install-forgeos.sh'

usage() {
  cat <<'EOF'
install-forgeos -- prepare a local `forgeos` command on Linux

Usage:
  install-forgeos.sh --destination <dir> [--source <dir>] [--apply] [--json]
  install-forgeos.sh --destination <dir> --uninstall [--apply] [--json]
  install-forgeos.sh --help

Writes one launcher into --destination and nothing else. DRY RUN unless --apply is given.
PATH is never changed: the line to add is reported for you to apply yourself.
It fetches nothing, and --force is neither accepted nor passed.

Linux. macOS is not claimed: it has never run there in CI (open question 002).

Exit codes: 0 reported, help included - 1 usage error, missing source, bad destination,
            or bad checksum.
EOF
}

# --- help: the only path that exits 0 without doing anything --------------------------------------
# Asking what a program does is not a usage error, and answering it on stderr with exit 1 tells every
# script that reads exit codes that the question failed. The Windows half learned this the hard way
# in M-22.2b; this one is born with it. Help is checked before any argument is interpreted, so it
# cannot be reached only by a well-formed command line.
for _arg in "$@"; do
  case "$_arg" in
    -h|--help|help)
      usage           # stdout, not stderr: this is the answer, not a complaint about the question
      exit 0
      ;;
  esac
done

SOURCE=''
DESTINATION=''
APPLY=0
UNINSTALL=0
JSON=0

while [ $# -gt 0 ]; do
  case "$1" in
    --source)      shift; SOURCE="${1:-}" ;;
    --source=*)    SOURCE="${1#--source=}" ;;
    --destination) shift; DESTINATION="${1:-}" ;;
    --destination=*) DESTINATION="${1#--destination=}" ;;
    --apply)       APPLY=1 ;;
    --uninstall)   UNINSTALL=1 ;;
    --json)        JSON=1 ;;
    '') ;;
    # --force lands here and is refused by name rather than ignored. Silently accepting a flag that
    # does nothing is how a caller comes to believe it did something.
    *) echo "Unknown option: $1" >&2; echo '' >&2; usage >&2; exit 1 ;;
  esac
  shift
done

notes=()

# --- the source -----------------------------------------------------------------------------------
[ -n "$SOURCE" ] || SOURCE="$(cd "$SELF_DIR/../.." && pwd)"
if [ ! -d "$SOURCE" ]; then
  echo "Source is not a directory: $SOURCE" >&2
  exit 1
fi
src_root="$(cd "$SOURCE" && pwd)"

# A source is only a ForgeOS if it carries the command this installer points at. Checking for the
# entry point rather than for a name means a renamed directory still works and an empty one does not.
src_cmd="$src_root/scripts/command/forgeos.sh"
if [ ! -f "$src_cmd" ]; then
  echo "Source does not look like ForgeOS (no scripts/command/forgeos.sh): $src_root" >&2
  echo 'Point --source at an extracted release artifact or a checkout.' >&2
  exit 1
fi

src_version='unknown'
if [ -f "$src_root/blueprint.version" ]; then
  v="$(grep -m1 '"version"' "$src_root/blueprint.version" | sed 's/.*: *"//; s/".*//')"
  [ -n "$v" ] && src_version="$v"
else
  notes+=('the source has no blueprint.version, so the version it installs is unknown')
fi

# --- integrity --------------------------------------------------------------------------------------
# A published artifact ships a .sha256 beside it. A checkout does not, and saying so is the point:
# a verification step that silently does nothing is worse than one that reports it had nothing to do.
#
# The digest tool is chosen BY CAPABILITY, NOT BY NAME -- the house rule this repository has already
# paid for once. sha256sum is GNU, shasum is what macOS and the BSDs ship, and openssl is the last
# resort; each is probed by actually hashing something before it is trusted.
sha256_of() {   # sha256_of <file> -> lowercase hex, or nothing
  if command -v sha256sum >/dev/null 2>&1 && printf '' | sha256sum >/dev/null 2>&1; then
    sha256sum "$1" 2>/dev/null | awk '{print tolower($1)}'
  elif command -v shasum >/dev/null 2>&1 && printf '' | shasum -a 256 >/dev/null 2>&1; then
    shasum -a 256 "$1" 2>/dev/null | awk '{print tolower($1)}'
  elif command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 "$1" 2>/dev/null | awk '{print tolower($NF)}'
  fi
}

integrity='none'
integrity_detail='no checksum file beside the source; a git checkout gets its integrity from git instead'
src_parent="$(dirname "$src_root")"
archive_sum=''
for cand in "$src_parent"/*.tar.gz.sha256; do
  [ -f "$cand" ] && { archive_sum="$cand"; break; }
done

if [ -n "$archive_sum" ]; then
  expected=''
  named=''
  line="$(head -1 "$archive_sum" 2>/dev/null)"
  # The sha256sum format: digest, whitespace, an optional '*' for binary mode, then the name.
  if printf '%s' "$line" | grep -qE '^[0-9a-fA-F]{64}[[:space:]]+\*?.+$'; then
    expected="$(printf '%s' "$line" | awk '{print tolower($1)}')"
    named="$(printf '%s' "$line" | sed 's/^[0-9a-fA-F]\{64\}[[:space:]]*//; s/^\*//')"
  fi
  target="$src_parent/$named"
  if [ -z "$expected" ]; then
    integrity='unreadable'
    integrity_detail="the checksum file beside the source could not be parsed: $(basename "$archive_sum")"
  elif [ ! -f "$target" ]; then
    integrity='unverified'
    integrity_detail="a checksum file names $named, but that archive is not beside it"
  else
    actual="$(sha256_of "$target")"
    if [ -z "$actual" ]; then
      # No usable digest tool. This is NOT treated as a pass: an unverifiable artifact is reported
      # as unverified, never as verified, and the reason names the missing tool.
      integrity='unverified'
      integrity_detail='no working sha256 tool found (tried sha256sum, shasum -a 256, openssl dgst)'
    elif [ "$actual" = "$expected" ]; then
      integrity='verified'
      integrity_detail="$named matches its published SHA-256"
    else
      # FAIL CLOSED. This is the one branch that must never become a warning.
      echo 'Checksum mismatch. Refusing to install.' >&2
      echo "  archive  : $target" >&2
      echo "  expected : $expected" >&2
      echo "  actual   : $actual" >&2
      exit 1
    fi
  fi
fi

# --- the destination --------------------------------------------------------------------------------
if [ -z "$DESTINATION" ]; then
  echo '--destination <dir> is required: where the forgeos launcher should be written.' >&2
  echo '' >&2
  usage >&2
  exit 1
fi
dest_parent="$(dirname "$DESTINATION")"
if [ -n "$dest_parent" ] && [ ! -d "$dest_parent" ]; then
  echo "Destination's parent directory does not exist: $dest_parent" >&2
  exit 1
fi
if [ -d "$DESTINATION" ]; then
  dest_full="$(cd "$DESTINATION" && pwd)"
else
  dest_full="$(cd "$dest_parent" && pwd)/$(basename "$DESTINATION")"
fi

# Writing a launcher into the ForgeOS directory itself would put a copy of the command beside the
# command.
if [ "${dest_full%/}" = "${src_root%/}" ]; then
  echo 'Destination and source are the same directory. Choose a separate directory for the launcher.' >&2
  exit 1
fi

launcher="$dest_full/forgeos"

is_our_launcher() {   # is_our_launcher <path>
  [ -f "$1" ] || return 1
  grep -qF "$MARKER" "$1" 2>/dev/null
}

# A file in the destination that is NOT ours is never touched, in either mode. The installer owns
# what it wrote and nothing else.
blockers=()
if [ -e "$launcher" ] && ! is_our_launcher "$launcher"; then
  blockers+=("forgeos exists in the destination and was not written by this installer; it is left untouched")
fi

# --- PATH: reported, never changed ------------------------------------------------------------------
on_path=false
case ":${PATH:-}:" in
  *":${dest_full%/}:"*) on_path=true ;;
esac

mode='dry-run'
[ "$APPLY" -eq 1 ] && mode='apply'
action='install'
[ "$UNINSTALL" -eq 1 ] && action='uninstall'

planned=()
written=()
removed=()

if [ "$UNINSTALL" -eq 1 ]; then
  if is_our_launcher "$launcher"; then
    planned+=("$launcher")
    if [ "$APPLY" -eq 1 ]; then
      rm -f "$launcher"
      removed+=("$launcher")
    fi
  fi
else
  if [ "${#blockers[@]}" -eq 0 ]; then
    planned+=("$launcher")
  fi
  if [ "$APPLY" -eq 1 ] && [ "${#blockers[@]}" -eq 0 ]; then
    [ -d "$dest_full" ] || mkdir -p "$dest_full"
    # The launcher carries no logic of its own beyond locating the command. Anything smarter here
    # would be a second implementation of the wrapper, and the two would drift.
    # "$@" is quoted so an argument containing a space survives the hop; unquoted $@ would split
    # `--target "/some/dir with spaces"` back into two arguments at the wrapper.
    {
      printf '%s\n' '#!/usr/bin/env bash'
      printf '%s\n' "# $MARKER"
      printf '%s\n' "# source: $src_root"
      printf '%s\n' "exec bash \"$src_cmd\" \"\$@\""
    } > "$launcher"
    # Executable, or it is a text file rather than a command. This has no Windows counterpart and is
    # the whole difference between installed and merely present.
    chmod +x "$launcher"
    written+=("$launcher")
  fi
fi

exit_code=0
if [ "${#blockers[@]}" -gt 0 ] && [ "$UNINSTALL" -ne 1 ]; then exit_code=1; fi

# --- output -----------------------------------------------------------------------------------------
jesc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
jarr() {   # jarr <newline-separated>
  if [ -z "$1" ]; then printf '[]'; return; fi
  printf '['
  local first=1 item
  while IFS= read -r item; do
    [ -z "$item" ] && continue
    [ "$first" -eq 1 ] && first=0 || printf ', '
    printf '"%s"' "$(jesc "$item")"
  done <<EOF
$1
EOF
  printf ']'
}

if [ "$JSON" -eq 1 ]; then
  wrote_flag=false; [ "$APPLY" -eq 1 ] && wrote_flag=true
  cat <<EOF
{
  "schema": "forgeos.install/1",
  "platform": "linux",
  "action": "$action",
  "mode": "$mode",
  "wouldWrite": $wrote_flag,
  "source": "$(jesc "$src_root")",
  "sourceVersion": "$(jesc "$src_version")",
  "destination": "$(jesc "$dest_full")",
  "integrity": "$integrity",
  "integrityNote": "$(jesc "$integrity_detail")",
  "pathChanged": false,
  "destinationOnPath": $on_path,
  "pathLine": "$(jesc "$dest_full")",
  "plannedFiles": $(jarr "$(printf '%s\n' ${planned[@]+"${planned[@]}"})"),
  "filesWritten": $(jarr "$(printf '%s\n' ${written[@]+"${written[@]}"})"),
  "filesRemoved": $(jarr "$(printf '%s\n' ${removed[@]+"${removed[@]}"})"),
  "blockers": $(jarr "$(printf '%s\n' ${blockers[@]+"${blockers[@]}"})"),
  "notes": $(jarr "$(printf '%s\n' ${notes[@]+"${notes[@]}"})"),
  "forcePassed": false,
  "safety": {
    "canModifyFiles": $wrote_flag,
    "canAuthorizeCode": false,
    "canOpenGovernanceWindow": false,
    "changesPath": false,
    "reachesNetwork": false
  }
}
EOF
  exit "$exit_code"
fi

up_mode="$(printf '%s' "$mode" | tr 'a-z' 'A-Z')"
echo ''
printf 'ForgeOS installer  [%s]  %s\n' "$up_mode" "$action"
echo ''
printf '  %-22s %s\n' 'source' "$src_root"
printf '  %-22s %s\n' 'source version' "$src_version"
printf '  %-22s %s\n' 'destination' "$dest_full"
printf '  %-22s %s  (%s)\n' 'integrity' "$integrity" "$integrity_detail"
echo ''

if [ "${#blockers[@]}" -gt 0 ]; then
  echo '  refusing to write:'
  for b in "${blockers[@]}"; do printf '    - %s\n' "$b"; done
  echo ''
fi

if [ "$UNINSTALL" -eq 1 ]; then
  if [ "${#planned[@]}" -eq 0 ]; then
    printf '  %-22s %s\n' 'nothing to remove' 'no launcher carrying this installer'"'"'s marker is here'
  fi
  for p in ${planned[@]+"${planned[@]}"}; do
    if [ "$APPLY" -eq 1 ]; then printf '  %-22s %s\n' 'removed' "$p"
    else printf '  %-22s %s\n' 'would remove' "$p"; fi
  done
else
  for p in ${planned[@]+"${planned[@]}"}; do
    if [ "$APPLY" -eq 1 ]; then printf '  %-22s %s\n' 'wrote' "$p"
    else printf '  %-22s %s\n' 'would write' "$p"; fi
  done
fi

echo ''
printf '  %-22s %s\n' 'PATH changed' 'no -- never, by design'
if [ "$on_path" = true ]; then
  printf '  %-22s %s\n' 'destination on PATH' 'yes'
else
  printf '  %-22s %s\n' 'destination on PATH' 'no. To add it for this session:'
  printf '    export PATH="%s:$PATH"\n' "$dest_full"
fi
for n in ${notes[@]+"${notes[@]}"}; do printf '  %-22s %s\n' 'note' "$n"; done

echo ''
if [ "$APPLY" -ne 1 ]; then
  echo '  This was a DRY RUN. Nothing was written.'
  echo '  To apply it:'
  printf '    bash scripts/install/install-forgeos.sh --destination "%s" --apply\n' "$dest_full"
  echo ''
fi
echo '  This installer fetches nothing, changes no PATH, and never passes --force.'
echo '  Linux. macOS is not claimed until it runs there in CI (open question 002).'
echo ''

exit "$exit_code"
